# Generated by Django 3.1.4 on 2021-01-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=50000)),
                ('fname', models.CharField(default='', max_length=50)),
                ('sname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('number', models.IntegerField(default=1)),
                ('address1', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('zipcode', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
