# Generated by Django 3.1.4 on 2021-01-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210103_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
