# Generated by Django 3.1.4 on 2021-01-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210103_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=50000)),
                ('fname', models.CharField(default='', max_length=50)),
                ('sname', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=1000)),
                ('number', models.CharField(default='', max_length=1000)),
                ('address1', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=1000)),
                ('zipcode', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
